### ISSUE TITLE
Unable to compile using Visual Studio Community Edition | ./build command

### ISSUE THREAD

**Issue by codebased** [Particular/Workshop#304]
Any idea? 

Unhandled Exception: System.Exception: The following target was not found: exercise.
   at Bullseye.Internal.TargetCollection.Validate(List`1 names) in C:\projects\bullseye\Bullseye\Internal\TargetCollection.cs:line 99
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies, Boolean dryRun, Logger log) in C:\projects\bullseye\Bullseye\Internal\TargetCollection.cs:line 28
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies, Boolean dryRun, Logger log) in C:\projects\bullseye\Bullseye\Internal\TargetCollection.cs:line 37
   at Bullseye.Internal.TargetCollectionExtensions.RunAsync(TargetCollection targets, List`1 args, IConsole console) in C:\projects\bullseye\Bullseye\Internal\TargetCollectionExtensions.cs:line 116
   at Bullseye.Targets.RunTargets(IEnumerable`1 args) in C:\projects\bullseye\Bullseye\Targets.Sync.cs:line 34
   at Program.Main(String[] args) in C:\Users\codeb\Documents\gits\Workshop\targets\Program.cs:line 24
PS C:\Users\codeb\Documents\gits\Workshop>

**Comment by adamralph** [comment]
Hey @codebased, this is just because the target is named `exercises`, not `exercise`.

I..e. `.\build.cmd exercises` should work.

**Comment by codebased** [comment]
@adamralph I did find the reason behind later :) Thanks for your reply.
